# Generated by Django 2.2 on 2021-04-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
